name: build

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack pnpm@10.34.5 install --no-frozen-lockfile

      - name: Type Check
        run: pnpm check

      - name: Build
        run: pnpm build
