name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: corepack pnpm@10.34.5 install --no-frozen-lockfile
      - name: Build site
        run: pnpm build
      - run: echo 'antv.vision' > dist/CNAME
      - run: |
          cd dist
          git init
          git config --local user.name antv
          git config --local user.email github@antv.vision
          git add .
          git commit -m "update by release action"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          directory: dist
          branch: gh-pages
          force: true
